# Site settings
title: The Signs Of Austin
email: reagan@reaganray.com
description: > # this means to ignore newlines until "baseurl:"
  100 illustrations to document Austin’s rich history.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thesignsofaustin.com" # the base hostname & protocol for your site
twitter_username: raygunray
github_username:  raygunray
permalink: /:title/


# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 10
port:    4000
